MyJersey/MyJersey/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
path('admin/', admin.site.urls),
path('cart/', include('cart.urls', namespace='cart')),
path('orders/', include('orders.urls', namespace='orders')),
path('payment/', include('payment.urls', namespace='payment')),
path('coupons/', include('coupons.urls', namespace='coupons')),
path('', include('store.urls', namespace='store')),
)


# urlpatterns = i18n_patterns(
#     path('admin/', admin.site.urls),
#     path('cart/',include('cart.urls',namespace='cart')),
#     path('orders/',include('orders.urls',namespace='orders')),
#     path('payment/', include('payment.urls', namespace='payment')),
#     path('coupons',include('coupons.urls', namespace='coupons')),
#     path('rosetta/', include('rosetta.urls')),
#     path('',include('store.urls',namespace='store')),
    
# )

MyJersey/cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'
urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove')
]

MyJersey/coupons/urls.py
from django.urls import path
from .import views

app_name = 'coupons'
urlpatterns = [
    path('apply/',views.coupon_apply,name='apply'),
]

MyJersey/orders/urls.py
from django.urls import path
from .import views


app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    #path('create/',views.order_create,name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',views.admin_order_pdf,name='admin_order_pdf'),
]

MyJersey/store/urls.py
from django.urls import path
from . import views
app_name = 'store'

urlpatterns = [
    path('',views.main,name='main'),
    path('<slug:category_slug>/',views.main,name='prod_list_by_category'),
    path('<int:id>/<slug:slug>/',views.prod_details,name="prod_details"),
    path("cart/",views.cart, name="cart"),
    path('checkout/',views.checkout,name="checkout")
]

MyJersey/cart/models.py
from django.db import models

# Create your models here.

MyJersey/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,11)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

MyJersey/cart/views.py
from coupons.views import coupon_apply
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from store.recommender import Recommender

@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    if cart:
        return redirect('cart:cart_detail')
    return redirect('/')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'],'override':True})
    coupon_apply_form = CouponApplyForm()
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended_products = r.suggest_products_for(cart_products,max_results=4)
    return render(request,'cart/detail.html',{'cart':cart,'coupon_apply_form':coupon_apply_form,'recommended_products':recommended_products})

MyJersey/cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Your Shopping Cart
{% endblock %}

{% block content %}
    <h1>Your Shopping Cart</h1>
    <table class="cart">
        <thead>
            
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove<th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
        </thead>
    </tbody>
        
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'images/no_image.png' %}{% endif %}" alt="">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cart:cart_add'  product.id %}" method="POST">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.override }}
                        <br>
                        <br>
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td>
                    <form action="{% url 'cart:cart_remove' product.id %}" method="POST">
                        <input type="submit" value="Remove">
                        {% csrf_token %}
                    </form> 
                </td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <!-- <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr> -->
       
        {% if cart.coupon %}
           <tr class="subtotal">
               <td>Subtotal</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
           </tr>
           <tr>
               <td>
                   {{ cart.coupon.code }} coupon
                   ({{  cart.coupon.discount }}% off)
               </td>
               <td colspan="4"></td>
               <td class="num neg">
                   -$ {{ cart.get_discount|floatformat:2 }}
               </td>
           </tr>     
        {% endif %}
        <tr class="Total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">
                ${{  cart.get_total_price_after_discount|floatformat:2 }}
            </td>
        </tr>
    </tbody>
    </table>
    
    {% if recommended_products %}
        <div class="recommendations cart">
        {% for p in recommended_products %}
        <div class="item">
        <a href="{{ p.get_absolute_url }}">
        <img src="{% if p.image %}{{ p.image.url }}{% else %}
        {% static "image/no_image.png" %}{% endif %}">
        </a>
        <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
        </div>
        {% endfor %}
        </div>
        {% endif %}

    <p>Apply Coupon:</p>
    <form action="{% url 'coupons:apply' %}" method="POST">
        {{  coupon_apply_form }}
        <input type="submit" value="Apply">
        {% csrf_token %}
    </form>
    <p class="text-right">
        <a href="{% url 'store:main' %}" class="button light">Continue Shopping</a>
        <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
    </p>
{% endblock %}